### ISSUE TITLE
Make these packages coexist with Ubuntu / KERN casacore packages.

### ISSUE THREAD

**Issue by confluence** [idia-astro/carta-casacore-deb#1]
These packages were originally designed to match the format of existing Ubuntu casacore packages, in the hopes that eventually we would be able to build just the CASA components we need against an unmodified casacore. But this may never happen, and having casacore packages which clash with the widely used KERN versions is going to cause issues, as demonstrated [here](https://github.com/CARTAvis/carta/issues/69). So we should repackage these to be installable in parallel with normal casacore packages.

**Comment by confluence** [comment]
This should be fixed in the latest builds in the PPA. This package now installs files to a custom location in `/opt`, and the backend packages have been rebuilt to look there for the headers and shared library files. This has not yet been fixed for the source build configuration and documentation in the upstream carta-casacore and carta-backend repos, but PRs are in progress.

**Comment by gijzelaerr** [comment]
awesome, great work
